// src/components/Home/Home.jsx
import React from "react";
import "./Home.scss"
import videoBg from "../../assets/videoBg.mp4"
import imgHeader from "../../assets/Text-14.png"
import ParallaxBg from "../../shared/ParallaxBg/ParallaxBg";
import Squares from "../../shared/Squares/Squares";




const Home = () => {

  return (
    <>
      <div className="container">
        <div className="backgoundParallaxBlack">
          <ParallaxBg Background="black"></ParallaxBg>
        </div>
        <div className="video-wrapper">
          <video loop width="100%" height="100%" preload="auto" autoPlay muted>
            <source src={videoBg} type="video/mp4" />
            Your browser does not support the video tag.
          </video>

          <div className="header">
            <img src={imgHeader} alt="" />
          </div>
        </div>

        <div className="backgoundParallaxRed">
          <ParallaxBg Background="red"></ParallaxBg>
        </div>

        <Squares></Squares>
      </div>
    </>
  );
};

export default Home;

// src/app/modules/home/home.component.ts
import { ChangeDetectorRef, Component, ElementRef, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})

export class HomeComponent implements OnInit {
  @ViewChild('data-scroll-container') public element!: ElementRef;
  scroll!: any;
  statement!:any;

  constructor(private elementRef: ElementRef, private changeDetector: ChangeDetectorRef) { }

  ngOnInit() {


  }


}

<div class="container" data-scroll-container>
  <div class="logo" data-scroll-section>
    <div class="loopText">
      <svg
        class="svgwave"
        xmlns="http://www.w3.org/2000/svg"
        width="301"
        height="21"
        viewBox="0 0 301 21"
      >
        <path
          id="wavepath"
          d="M 0 59 C 164 -128 290 41 459 63 M 458 62 C 304.6667 60.6667 124 448 -2 58"
        ></path>

        <text text-anchor="middle">
          <textPath class="my-text" side="left" href="#wavepath">
            <animate
              attributeName="startOffset"
              from="-100%"
              to="150%"
              begin="0s"
              dur="10s"
              repeatCount="indefinite"
              values="10%;0%"
            ></animate>

            HI THERE! I'M SAZKY A CREATIVE ART DIRECTOR, BASED IN SPAIN,
            FOLLOWING MY PASSIONS THROUGH ART, ADVERTISING AND CREATIVITY. ///
          </textPath>
        </text>
      </svg>
    </div>
  </div>
  <div class="video-wrapper" data-scroll-section>
    <video playsinline autoplay [muted]="'muted'" loop>
      <source
        src="../../../assets/img/DUKI, Jhayco - RoCKSTAR 2.0 (Video Oficial).mp4"
        type="video/mp4"
      />
      Your browser does not support the video tag.
    </video>

    <div class="header">
      <img src="../../../assets/img/Text-14.png" alt="" />
    </div>
  </div>

  <div class="logoBlack" data-scroll-section>
    <div class="loopText">
      <svg
        class="svgwave"
        xmlns="http://www.w3.org/2000/svg"
        width="301"
        height="21"
        viewBox="0 0 301 21"
      >
        <path
          id="wavepath"
          d="M 0 59 C 164 -128 290 41 459 63 M 458 62 C 304.6667 60.6667 124 448 -2 58"
        ></path>

        <text text-anchor="middle">
          <textPath class="my-text" side="left" href="#wavepath">
            <animate
              attributeName="startOffset"
              from="-100%"
              to="150%"
              begin="0s"
              dur="10s"
              repeatCount="indefinite"
              values="10%;0%"
            ></animate>

            HI THERE! I'M SAZKY A CREATIVE ART DIRECTOR, BASED IN SPAIN,
            FOLLOWING MY PASSIONS THROUGH ART, ADVERTISING AND CREATIVITY. ///
          </textPath>
        </text>
      </svg>
    </div>
  </div>

  <app-squares></app-squares>
</div>
