// src/app/shared/squares/squares.component.ts
import { Component, OnInit } from '@angular/core';
import { SquaresData } from 'src/app/utils/squaresData';

@Component({
  selector: 'app-squares',
  templateUrl: './squares.component.html',
  styleUrls: ['./squares.component.scss']
})
export class SquaresComponent implements OnInit {
  imageList!: any;

  constructor() { }

  ngOnInit() {
    this.imageList = SquaresData;
  }

}

  <div class="squares" data-scroll-section>
    <a [href]="item.url" class="squares-link" *ngFor="let item of this.imageList">
    <div class="inside-square" style="background-image: url({{item.img}})" >
      <h2>{{item.text}}</h2>
    </div>
    </a>
  </div>

// src/shared/Squares/Squares.jsx
import React from 'react';
import "./Squares.scss"
import { SquaresData } from '../../utils/SquaresData';

const Squares = () => {
    console.log('====================================');
    console.log(SquaresData);
    console.log('====================================');
    const squaresData = SquaresData;
    return (
        <>
            <div className="squares">
                {squaresData.map((square, index) => (
                    <a href={square.url} className="squares-link" key={index}>
                        <div
                            className="inside-square"
                            style={{ backgroundImage: `url(${square.img})` }}
                        >
                            <h2>{square.text}</h2>
                        </div>
                    </a>
                ))}
            </div>
        </>
    );
};

export default Squares;
