// src/app/shared/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { MatIconRegistry } from "@angular/material/icon";
import { DomSanitizer } from "@angular/platform-browser";

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {

  constructor(private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer
  ) {
    this.matIconRegistry.addSvgIcon(
      `facebook`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../../../assets/img/facebook.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `linkedin`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../../../assets/img/linkedin.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `instagram`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../../../assets/img/instagram.svg")
    );
  }

  ngOnInit() {
  }

}

<div class="footer-container">
  <h2>
    <a class="main-link" href="#">LEGEND.CO</a>
  </h2>

  <div class="rsss">
    <a href="https://www.facebook.com/ireyes7" target="_blank"><mat-icon svgIcon="facebook"></mat-icon></a>
    <a href="https://www.linkedin.com/in/ireyescarlos/" target="_blank"><mat-icon svgIcon="linkedin"></mat-icon></a>
    <a href="https://instagram.com/itl7?igshid=MzRlODBiNWFlZA==" target="_blank"><mat-icon svgIcon="instagram"></mat-icon></a>
  </div>
  <div class="routing">
    <span>
      <a href="#">CONTACT</a>
    </span>
    <span>
      <a href="#">FAQ</a>
    </span>
    <span>
      <a href="#">BLOG</a>
    </span>
  </div>
</div>

// src/shared/Footer/Footer.jsx
import React from "react";
import "./Footer.scss";
import facebookIcon from "../../assets/facebook.svg";
import instagramIcon from "../../assets/instagram.svg";
import linkedinIcon from "../../assets/linkedin.svg";

const Footer = () => {
  return (
    <>
      <div className="footer-container">
        <h2>
          <a className="main-link" href="#s">
            LEGEND.CO
          </a>
        </h2>

        <div className="rsss">
          <a
            href="https://www.facebook.com/ireyes7"
            target="_blank"
            rel="noreferrer"
          >
            <img src={facebookIcon} alt="" />
          </a>
          <a
            href="https://www.linkedin.com/in/ireyescarlos/"
            target="_blank"
            rel="noreferrer"
          >
            <img src={linkedinIcon} alt="" />
          </a>
          <a
            href="https://instagram.com/itl7?igshid=MzRlODBiNWFlZA=="
            target="_blank"
            rel="noreferrer"
          >
            <img src={instagramIcon} alt="" />
          </a>
        </div>
        <div className="routing">
          <span>
            <a href="#s">CONTACT</a>
          </span>
          <span>
            <a href="#s">FAQ</a>
          </span>
          <span>
            <a href="#s">BLOG</a>
          </span>
        </div>
      </div>
    </>
  );
};

export default Footer;
